# Generated by Django 4.0.2 on 2022-02-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract_status',
            options={'verbose_name': 'Contract_Status', 'verbose_name_plural': 'Contracts_Status'},
        ),
        migrations.AlterModelOptions(
            name='event_status',
            options={'verbose_name': 'Event_Status', 'verbose_name_plural': 'Events_Status'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_status',
        ),
        migrations.AddField(
            model_name='contract_status',
            name='contract',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='crm.contract'),
        ),
        migrations.AddField(
            model_name='event_status',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='crm.event'),
        ),
    ]
