# Generated by Django 4.0.2 on 2022-02-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_event_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_status',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='event_status',
            name='event',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='crm.contract_status'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='crm.event_status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(),
        ),
    ]
